Big refactoring and change answer response
OSLL/MD-Code_generator pull request #19
Opened 2021-10-26 23:04 UTC by neckbosov

Поменял формат ответа на json, обновил зависимости и переписал скрипт сборки, исправил багу, до этого запускался новый сервер внутри имеющегося, не понимаю как это нормально работало.

2021-11-04 14:03 UTC, HadronCollider requested changes
1. Во время запуска контейнера до запуска сервера следующие логи:
```
> Task :run
2021-11-04 13:55:48.594 [main] TRACE Application - {
    # application.conf @ file:/server/build/resources/main/application.conf: 6
    "application" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 7
        "modules" : [
            # application.conf @ file:/server/build/resources/main/application.conf: 7
            "com.example.ApplicationKt.module"
        ]
    },
    # application.conf @ file:/server/build/resources/main/application.conf: 2
    "deployment" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 3
        "port" : 8080
    },
    # Content hidden
    "security" : "***"
}

2021-11-04 13:55:49.483 [main] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
2021-11-04 13:55:51.961 [main] INFO  ktor.application - No ktor.deployment.watch patterns specified, automatic reload is not active
```
2. После обновленного запуска отсутствуют какие-либо логи в stdout (даже простейшие, сообщающие о пришедшем запросе):
```
2021-11-04 13:55:52.057 [main] INFO  ktor.application - Responding at http://0.0.0.0:8080
<==========---> 80% EXECUTING [6m 55s]
> :run
```

2021-11-09 15:46 UTC, neckbosov commented
Я попробовал запустить контейнер по инструкции, логи о запросах выводятся. Можешь скинуть более подробные скины и команды для запуска?

2021-11-09 16:08 UTC, HadronCollider commented
> Я попробовал запустить контейнер по инструкции, логи о запросах выводятся. Можешь скинуть более подробные скины и команды для запуска?

Команда `docker logs *container_id*`
```
$ docker logs c872af8027dd
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :run
2021-11-09 16:03:02.837 [main] TRACE Application - {
    # application.conf @ file:/server/build/resources/main/application.conf: 6
    "application" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 7
        "modules" : [
            # application.conf @ file:/server/build/resources/main/application.conf: 7
            "com.example.ApplicationKt.module"
        ]
    },
    # application.conf @ file:/server/build/resources/main/application.conf: 2
    "deployment" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 3
        "port" : 8080
    },
    # Content hidden
    "security" : "***"
}

2021-11-09 16:03:03.130 [main] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
2021-11-09 16:03:03.789 [main] INFO  ktor.application - No ktor.deployment.watch patterns specified, automatic reload is not active
2021-11-09 16:03:03.816 [main] INFO  ktor.application - Responding at http://0.0.0.0:8080
<==========---> 80% EXECUTING [2m 24s]
```

Какое бы количество запросов не приходило - stdout/stderr пусты после `[main] INFO  ktor.application - Responding at http://0.0.0.0:8080
`
```
$ docker logs c872af8027dd
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :run
2021-11-09 16:03:02.837 [main] TRACE Application - {
    # application.conf @ file:/server/build/resources/main/application.conf: 6
    "application" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 7
        "modules" : [
            # application.conf @ file:/server/build/resources/main/application.conf: 7
            "com.example.ApplicationKt.module"
        ]
    },
    # application.conf @ file:/server/build/resources/main/application.conf: 2
    "deployment" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 3
        "port" : 8080
    },
    # Content hidden
    "security" : "***"
}

2021-11-09 16:03:03.130 [main] INFO  Application - No ktor.deployment.watch patterns specified, automatic reload is not active
2021-11-09 16:03:03.789 [main] INFO  ktor.application - No ktor.deployment.watch patterns specified, automatic reload is not active
2021-11-09 16:03:03.816 [main] INFO  ktor.application - Responding at http://0.0.0.0:8080
<==========---> 80% EXECUTING [4m 23s]
> :run
```

2021-11-09 18:20 UTC, neckbosov commented
У меня работает
Процесс:
```
> Task :run
2021-11-09 18:15:43.179 [main] TRACE Application - {
    # application.conf @ file:/server/build/resources/main/application.conf: 6
    "application" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 7
        "modules" : [
            # application.conf @ file:/server/build/resources/main/application.conf: 7
            "com.example.ApplicationKt.module"
        ]
    },
    # application.conf @ file:/server/build/resources/main/application.conf: 2
    "deployment" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 3
        "port" : 8080
    },
    # Content hidden
    "security" : "***"
}

2021-11-09 18:15:43.229 [main] INFO  Application - Autoreload is disabled because the development mode is off.
2021-11-09 18:15:43.522 [main] INFO  Application - Responding at http://0.0.0.0:8080
2021-11-09 18:15:43.523 [main] INFO  Application - Application started in 0.303 seconds.
2021-11-09 18:15:43.524 [main] TRACE Application - Application started: io.ktor.application.Application@3a62c01e
2021-11-09 18:16:27.539 [eventLoopGroupProxy-4-1] TRACE Application - 200 OK: GET - /
2021-11-09 18:16:27.590 [eventLoopGroupProxy-4-1] TRACE Application - 404 Not Found: GET - /favicon.ico
```
Логи:
```
docker logs condescending_herschel                                                                  ✔ 
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :run
2021-11-09 18:15:43.179 [main] TRACE Application - {
    # application.conf @ file:/server/build/resources/main/application.conf: 6
    "application" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 7
        "modules" : [
            # application.conf @ file:/server/build/resources/main/application.conf: 7
            "com.example.ApplicationKt.module"
        ]
    },
    # application.conf @ file:/server/build/resources/main/application.conf: 2
    "deployment" : {
        # application.conf @ file:/server/build/resources/main/application.conf: 3
        "port" : 8080
    },
    # Content hidden
    "security" : "***"
}

2021-11-09 18:15:43.229 [main] INFO  Application - Autoreload is disabled because the development mode is off.
2021-11-09 18:15:43.522 [main] INFO  Application - Responding at http://0.0.0.0:8080
2021-11-09 18:15:43.523 [main] INFO  Application - Application started in 0.303 seconds.
2021-11-09 18:15:43.524 [main] TRACE Application - Application started: io.ktor.application.Application@3a62c01e
2021-11-09 18:16:27.539 [eventLoopGroupProxy-4-1] TRACE Application - 200 OK: GET - /
2021-11-09 18:16:27.590 [eventLoopGroupProxy-4-1] TRACE Application - 404 Not Found: GET - /favicon.ico
> IDLE
> :run
> IDLE
```

2021-11-09 18:41 UTC, neckbosov commented
Проверь пожалуйста та ли ветка и пересобери контейнер, Я не могу это воспроизвести, у меня все работает

2021-11-09 18:43 UTC, HadronCollider commented
Пока второе замечание про логи оставим, что с первым о `TRACE Application`?

2021-11-09 19:12 UTC, neckbosov commented
у меня и они есть, попробуй на самом деле пересобрать контейнер

2021-11-10 12:55 UTC, HadronCollider commented
Проблема с логами запросов действительно была на моей стороне - теперь они есть
Однако для запроса `localhost:8080/check_answer?task=10&rand_seed=variant_2&variables_num=6&arguments_num=3&printf_num=3&answer=D%5B1%2C%200%2C%203%5D` следующий трейсбек:
```
2021-11-10 12:53:55.744 [eventLoopGroupProxy-4-1] ERROR Application - 300 Multiple Choices: GET - /check_answer

java.lang.IllegalArgumentException: Response pipeline couldn't transform 'class com.example.AnswerResponse' to the OutgoingContent

        at io.ktor.server.engine.BaseApplicationResponse$Companion$setupSendPipeline$1.invokeSuspend(BaseApplicationResponse.kt:311)

        at io.ktor.server.engine.BaseApplicationResponse$Companion$setupSendPipeline$1.invoke(BaseApplicationResponse.kt)

        at io.ktor.server.engine.BaseApplicationResponse$Companion$setupSendPipeline$1.invoke(BaseApplicationResponse.kt)

        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)

        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)

        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)

        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)

        at com.example.ServerKt$congigureServer$1$5.invokeSuspend(Server.kt:708)

        at com.example.ServerKt$congigureServer$1$5.invoke(Server.kt)

        at com.example.ServerKt$congigureServer$1$5.invoke(Server.kt)

        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)

        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)

        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)

        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)

        at io.ktor.routing.Routing.executeResult(Routing.kt:155)

        at io.ktor.routing.Routing.interceptor(Routing.kt:39)

        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)

        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)

        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)

        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)

        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)

        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:188)

        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)

        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)

        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)

        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)

        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)

        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)

        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:127)

        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)

        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)

        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)

        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)

        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)

        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)

        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:123)

        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)

        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)

        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)

        at kotlinx.coroutines.BuildersKt__Builders_commonKt.startCoroutineImpl(Builders.common.kt:194)

        at kotlinx.coroutines.BuildersKt.startCoroutineImpl(Unknown Source)

        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134)

        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)

        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)

        at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:43)

        at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:34)

        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)

        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)

        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)

        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)

        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)

        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:251)

        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

        at java.base/java.lang.Thread.run(Thread.java:829)
```

2021-11-16 12:43 UTC, HadronCollider approved these changes

2021-11-16 12:43 UTC, merged